default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: catawbariverkeeper_development
test:
  <<: *default
  database: catawbariverkeeper_test
